### ISSUE TITLE
Add Bookmark Bar Toggle to Sidebar Settings

### ISSUE THREAD

**Issue by ZeeshanMukhtar1** [XengShi/materialYouNewTab#262]
Add a toggle option in the sidebar to control the visibility of the browser's bookmarks bar. The toggle should integrate with the existing settings and allow users to enable or disable the bookmarks bar directly from the New Tab interface. Ensure it matches the Material You design and persists user preferences.

### Toggle Implementation:
Add a toggle labeled "Show Bookmarks Bar" to the sidebar settings menu.
The toggle's initial state should reflect the current visibility of the bookmarks bar (fetch the setting on load).

### Functionality:
When the toggle is enabled, the bookmarks bar should become visible.
When the toggle is disabled, the bookmarks bar should be hidden.

**Comment by itz-rj-here** [comment]
@ZeeshanMukhtar1 Yeah I was working on it but It might take me too much time than i expected. To make a sidebar for bookmark with proper functionality, we have to add the bookmark api's on the files. Also to make the design looks good with the current UI, We need to make a proper css code too.

**Comment by prem-k-r** [comment]
> Hi, could you please assign me the issue to add a bookmarks bar toggle in the sidebar settings?

@XengShi

**Comment by ZeeshanMukhtar1** [comment]
> @ZeeshanMukhtar1 Yeah I was working on it but It might take me too much time than i expected. To make a sidebar for bookmark with proper functionality, we have to add the bookmark api's on the files. Also to make the design looks good with the current UI, We need to make a proper css code too.

Okay, if you are working on it, you can continue. I don't want your changes to be wasted in the code.

**Comment by itz-rj-here** [comment]
> > @ZeeshanMukhtar1 Yeah I was working on it but It might take me too much time than i expected. To make a sidebar for bookmark with proper functionality, we have to add the bookmark api's on the files. Also to make the design looks good with the current UI, We need to make a proper css code too.
> 
> Okay, if you are working on it, you can continue. I don't want your changes to be wasted in the code.

That's not how I started. I was researching the bookmarks' APIs. I was attempting to learn about the bookmark's APIs in order to figure out how to implement this functionality into the extension. However, it could take a long time to fully understand the APIs. In addition, I'm dealing with some personal issues right now. For a few weeks, I might not be able to log on.
You seem to be a developer as well. according to the activity on your GitHub profile. You can begin coding the bookmark right now if you so choose. I'll check your changes in my spare time if I have it.
