### ISSUE TITLE
Can't debug without changing a line in manifest.json

### ISSUE THREAD

**Issue by ZiClaud** [XengShi/materialYouNewTab#63]
When I use the default manifest.json to debug, this error message appears on Firefox (I'm on Linux Fedora, idk if that changes anything)

![Screenshot from 2024-10-15 23-43-11](https://github.com/user-attachments/assets/c1c96ed8-03f2-43f0-a3de-c495cdadb96e)

But changing just one line (line 11) in `manifest.json` fixes the problem, and it lets me debug
```
    "background": {
        "scripts": ["background.js"]
    },
```

I want to know if it's just my problem, or if others found it too.
And if it's possible to change it without breaking anything in other browsers.

**Comment by XengShi** [comment]
Yes, I forgot to mention that! My mistake. Firefox requires a slightly different manifest file, which I’ve already used in the extension available on the Mozilla store. Since the extension can be easily downloaded from there, I didn’t add the Firefox-specific manifest.json file here on GitHub.

here is the manifest file for firefox
[manifest(firefox).json](https://github.com/user-attachments/files/17402075/manifest.firefox.json)

**Comment by ZiClaud** [comment]
Thank you!
